# Generated by Django 5.1.2 on 2024-10-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок блога')),
                ('description', models.TextField(verbose_name='Описание блога')),
                ('image', models.ImageField(upload_to='image_blog/', verbose_name='Фото блога')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': ' настройка ',
                'verbose_name_plural': 'настройки ',
            },
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
